app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

//página inicial da aplicação.
Route::get('/', ['as' => 'welcome', 'uses' => 'WelcomeController@index']);


//relacionado aos perfis de usuário.


//rota para o usuário acessar o seu perfil.
Route::get('profile',['as' => 'profile', 'uses' => 'HomeController@profile']);

//rota para que a entidade possa acessar o seu perfil.
Route::get('profile-entity',['as' => 'profile.entity', 'uses' => 'HomeController@profileEntity']);

Route::get('profile/busca', ['as' => 'profile.busca', 'uses' => 'HomeController@busca']);

Route::get('profile/{id}', ['as' => 'profile.details', 'uses' => 'HomeController@details']);

Route::delete('profile/{id}', ['as' => 'profile.destroy', 'uses' => 'HomeController@destroy']);

//pagina home com  a lista de perfis.
Route::get('home', ['as' => 'home', 'uses' => 'HomeController@home']);

//página com a lista de entidades.
Route::get('entidades', ['as' => 'entidades', 'uses' => 'EntidadeController@entidades']);

Route::get('entidades/create', ['as' => 'entidades.create', 'uses' => 'EntidadeController@create']);

Route::get('entidades/{id}', ['as' => 'entidades.details', 'uses' => 'EntidadeController@entidadesDetails']);

Route::post('entidades', ['as' => 'entidades.store', 'uses' => 'EntidadeController@store']);

//rotas relacionadas ao envio de imagem do perfil
Route::get('home/avatar', ['as' => 'avatar.create', 'uses' => 'HomeController@createAvatar']);
Route::post('home/avatar', ['as' => 'avatar.send', 'uses' => 'HomeController@sendAvatar']);

//logicas para seguir usuário...
Route::post('seguir', ['as' => 'seguir', 'uses' => 'HomeController@seguir']);

Route::post('deixar-de-seguir', ['as' => 'deixarDeSeguir', 'uses' => 'HomeController@deixarDeSeguir']);

Route::get('quem-me-segue', function(){
    return Auth::user()->theFriends()->count();
});

//controllers definidos para autenticação e restauração de senha.
Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

//serviço de integração com redes sociais.
Route::get('login/{provider?}', 'Auth\AuthController@login');

//resource controllers.
Route::resource("generolivro", 'GeneroLivroController');

Route::resource('posts', 'PostController');


//generos favoritos

Route::get('generos-favoritos/generos', ['as' => 'generosfavoritos.generos', 'uses' => 'GenerosFavoritosController@generos']);

Route::post('generos-favoritos/generos', ['as' => 'generosfavoritos.save', 'uses' => 'GenerosFavoritosController@save']);


//doação
Route::get('doacoes/{id}',['as' => 'doacoes.show', 'uses' => 'DoacaoController@show']);
Route::post('doacoes', ['as' => 'doacoes.send', 'uses' => 'DoacaoController@send']);
Route::put('doacoes', ['as' => 'doacoes.validar', 'uses' => 'DoacaoController@validar']);


//contato
Route::get('contato', ['as' => 'contato', 'uses' => 'ContatoController@contato']);

Route::post('contato', ['as' => 'contato.envia', 'uses' => 'ContatoController@enviaContato']);

Route::get('contato/{id}', ['as' => 'contato.ver', 'uses' => 'ContatoController@ver']);

Route::get('contatos', ['as' => 'contatos', 'uses' => 'ContatoController@listaContatos']);

resources/views/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <!--<meta http-equiv="refresh" content="5">-->
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="author" content="Aurélio Guedes">
    <meta name="keywords" content="Doações,Livros,Leia,Leitura,Literatura">
    <meta name="description" content="Um lugar para amantes da leitura">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Doe Livros - @yield('title')</title>

    <link rel="shortcut icon" type="image/png" href="/images/favicon-16.png"/>


	<link href="/css/app.css" rel="stylesheet">
    <!--<link href="/bower_components/bootstrap/dist/css/bootstrap.css" rel="stylesheet">-->

    <!--Bootstrap default -->
    <link href="/bower_components/bootstrap/dist/css/bootstrap.css" rel="stylesheet">

    <!-- Material Design for Bootstrap -->
    <link href="/bower_components/bootstrap-material-design/dist/css/roboto.min.css" rel="stylesheet">
    <link href="/bower_components/bootstrap-material-design/dist/css/material-fullpalette.min.css" rel="stylesheet">
    <link href="/bower_components/bootstrap-material-design/dist/css/ripples.min.css" rel="stylesheet">

    <!--social buttons -->
    <link href="/css/font-awesome.css" rel="stylesheet">
    <link href="/css/bootstrap-social.css" rel="stylesheet">

	<!-- Fonts -->
	<link href='//fonts.googleapis.com/css?family=Roboto:400,300' rel='stylesheet' type='text/css'>

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

    <!-- Jquery -->
    <script src="/bower_components/jquery/dist/jquery.js"></script>
</head>
<body>
	<nav class="navbar navbar-default">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle Navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				  <a class="navbar-brand" href="{{Auth::guest() ? route('welcome') : route('home')}}"><i class="glyphicon glyphicon-book"></i> Doe Livros</a>
			</div>

			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">

                    {{-- no lugar de false ficará o role do usuário como administrador --}}
                    @unless(Auth::guest() || !(Auth::user()->perfil == "administrador"))
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Cadastro<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{{route('entidades.create')}}"><i class="glyphicon glyphicon-plus"></i> Entidade</a></li>
                            <li><a href="{{route('generolivro.index')}}"><i class="glyphicon glyphicon-list"></i> Gênero de livros</a></li>
                            <li><a href="{{route('contatos')}}"><i class="glyphicon glyphicon-list"></i> Contatos</a></li>
                        </ul>
                    </li>
                    @endunless
                    @unless(Auth::guest())
                        <li><a href="{{route('entidades')}}">Entidades</a></li>
                    @endunless
				</ul>

				<ul class="nav navbar-nav navbar-right">
					@if (Auth::guest())
						<li><a href="/auth/login"><i class="glyphicon glyphicon-log-in"></i> Entrar</a></li>
						<li><a href="/auth/register"><i class="glyphicon glyphicon-plus"></i> Cadastrar</a></li>
					@else
                        <li>
                            @if(Auth::user()->perfil == "entidade")
                            <a href="{{route('profile.entity')}}"><img width="25" height="25" class="img-rounded" src="{{(Auth::user()->avatar) ? "/" . Auth::user()->avatar : "/images/default-profile-picture.png"}}" alt="Imagem do perfil de {{Auth::user()->name}}"/></a>
                                @else
                                <a href="{{route('profile')}}"><img width="25" height="25" class="img-rounded" src="{{(Auth::user()->avatar) ? "/" . Auth::user()->avatar : "/images/default-profile-picture.png"}}" alt="Imagem do perfil de {{Auth::user()->name}}"/></a>
                                @endif
                        </li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{ Auth::user()->name }} <span class="glyphicon glyphicon-option-vertical"></span></a>
							<ul class="dropdown-menu" role="menu">
                                @if(Auth::user()->perfil == "entidade")
                                    <li><a href="{{route('profile.entity')}}"><i class="glyphicon glyphicon-user"></i> Meu perfil</a> </li>
                                    @else
                                    <li><a href="{{route('profile')}}"><i class="glyphicon glyphicon-user"></i> Meu perfil</a> </li>
                                @endif
                                <li><a href="{{route('avatar.create')}}"><i class="glyphicon glyphicon-picture"></i> Editar avatar</a> </li>
								<li><a href="/auth/logout"><i class="glyphicon glyphicon-log-out"></i> Sair</a></li>
							</ul>
						</li>
					@endif
				</ul>
			</div>
		</div>
	</nav>

    <div class="container">
        @include('flash::message')
    </div>

	@yield('content')


	<!--<script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.1/js/bootstrap.min.js"></script>-->
    <script src="/md_bootstrap/js/bootstrap.min.js"></script>
    <!--<script src="/md_bootstrap/mdb.js"></script>-->
    <!-- Material Design for Bootstrap -->
    <script src="/bower_components/bootstrap-material-design/dist/js/material.min.js"></script>
    <script src="/bower_components/bootstrap-material-design/dist/js/ripples.min.js"></script>
    <script>
        $.material.init();
    </script>
</body>
</html>

resources/views/details.blade.php
@extends('app')


@section('title')
    {{$user->name}}
@endsection

@section('content')

    <div class="container">

        <div class="row">
            <div class="col-md-3">

                <center><img width="160" height="160" class="img-circle" src="/{{($user->avatar) ? $user->avatar : "images/default-profile-picture.png"}}" alt="Imagem do perfil de {{$user->name}}"></center>
                <hr/>
                <p class="text-center">{{$user->name}}</p>

                <br/><br/>
                <!--generos favoritos do perfil -->
                <div class="panel panel-success">

                    <div class="panel-heading panel-title text-center">Gêneros favoritos de <strong>{{$user->name}}</strong></div>

                    <div class="panel-body">
                        <ul class="list-group">
                            @if(isset($user))
                                @foreach($user->generolivros as $genero)
                                    <li class="list-group-item">{{$genero->nome}}</li>
                                @endforeach
                            @endif
                        </ul>
                    </div>

                </div>
            </div>

            <div class="col-lg-9">

                <div class="panel panel-default">
                    <div class="panel-heading panel-title text-center">Últimas postagens de {{$user->name}}</div>

                    <div class="panel-body">

                       @if($user->posts)
                        @foreach($user->posts->sortByDesc('created_at') as $post)

                            <div class="panel panel-success">

                                <div class="panel-heading panel-title text-right">{{date('d/m/Y à\s H:i', strtotime($post->created_at))}}</div>

                                <div class="panel-body">
                                    <div class="page-header">
                                        <h4><strong>{{$post->title}}</strong></h4>
                                    </div>

                                    <p>
                                        {{$post->body}}
                                    </p>
                                </div>
                            </div>

                        @endforeach

                       @endif

                    </div>
                </div>

            </div>
        </div>

    </div>

@endsection

resources/views/home.blade.php
@extends('app')

@section('title')
    Lista de perfis
@endsection

@section('content')
<div class="container">
	<div class="row">


        <div class="col-md-3">

            {{-- inclui os gênerosf --}}
            @include('partials.generos-favoritos')

        </div>

		<div class="col-md-9">

            <form action="{{route('profile.busca')}}" method="get" class="form-inline">
                <div class="form-group">
                    <input type="search" placeholder="Nome" name="name" id="name" class="form-control" required="" onfocus="" autofocus=""/>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">
                        <i class="glyphicon glyphicon-search"></i> Buscar
                    </button>
                </div>
            </form>

            <hr/>

            <br/>

			<div class="panel panel-default">

				<div class="panel-heading">Perfis</div>

                <div class="panel-body">

                    <div class="row">
                                @foreach($users as $user)
                                 <div class="col-sm-6 col-md-4">

                                    <div class="thumbnail hoverable">
                                        @if($user->perfil == "entidade")
                                            <a href="{{route('entidades.details', ['id' => $user->id])}}"><img class="img-circle" src="{{($user->avatar) ? '/' . $user->avatar : "/images/default-profile-picture.png"}}" alt="{{$user->name}}" height="100" width="100"></a>
                                            @else
                                            <a href="{{route('profile.details', ['id' => $user->id])}}"><img class="img-circle" src="{{($user->avatar) ? '/' . $user->avatar : "/images/default-profile-picture.png"}}" alt="{{$user->name}}" height="100" width="100"></a>
                                        @endif
                                        <div class="caption">
                                           <div class="page-header">
                                               <p>{{$user->name}} {{($user->id == Auth::user()->id) ? "(Eu)" : ""}}</p>
                                           </div>

                                            @if(!(Auth::user()->friends->contains($user->id)) && Auth::user()->id != $user->id)
                                                <form action="{{route('seguir')}}" method="post">
                                                    <input type="hidden" name="_token" value="{{csrf_token()}}"/>
                                                    <input type="hidden" name="user_id" value="{{$user->id}}"/>

                                                    <button type="submit" class="btn btn-danger btn-fab btn-raised mdi-action-grade" data-toggle="tooltip" data-placement="bottom" title="Adicionar aos favoritos">
                                                        Seguir
                                                    </button>
                                                </form>
                                            @endif

                                            @if((Auth::user()->id != $user->id) && (Auth::user()->friends->contains($user->id)))
                                                <form action="{{route('deixarDeSeguir')}}" method="post">
                                                    <input type="hidden" name="_token" value="{{csrf_token()}}"/>
                                                    <input type="hidden" name="user_id" value="{{$user->id}}"/>

                                                    <button type="submit" class="btn btn-success btn-fab btn-raised mdi-action-grade" data-toggle="tooltip" data-placement="bottom" title="Remover dos favoritos">
                                                        Deixar de seguir
                                                    </button>
                                                </form>
                                            @endif
                                        </div>
                                    </div>
                                 </div>
                                @endforeach
                    </div>

                </div>

                <div class="panel-footer text-center">
                    @unless($paginate == false)
                        {!! $users->render() !!}
                    @endunless
                </div>
			</div>
            <span class="spinner-blue">{{$users->count()}}</span> registro(s) encontrado(s) nesta pagina.
        </div>
	</div>
</div>
@endsection

resources/views/profile-entity.blade.php
@extends('app')

@section('title')
    {{$user->name}}
@endsection

@section('content')
    <div class="container">

        {{-- Error messages --}}
        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <strong>Opa!</strong> Existe algum problema com os valores informados<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <div class="row">
            <div class="col-md-3">
                <center><img width="160" height="160" class="img-circle" src="{{(Auth::user()->avatar) ? Auth::user()->avatar : "images/default-profile-picture.png"}}" alt="Imagem do perfil de {{Auth::user()->name}}"></center>
                <hr/>
                <p class="text-center">{{$user->name}}</p>
                <br/>
                <form action="{{route('profile.destroy', ['id' => Auth::user()->id])}}" method="post">
                    <input type="hidden" name="_token" value="{{csrf_token()}}"/>
                    <input type="hidden" name="_method" value="DELETE"/>

                    <center><button type="submit" class="btn btn-danger" disabled><i class="glyphicon glyphicon-remove"></i> Excluir conta</button></center>
                </form>
            </div>

            <div class="col-lg-9">

                <div class="row">

                    <!--form informations-->
                    <div class="col-md-12">

                        <div class="row">

                                <!-- tabs-->
                                <ul class="nav nav-tabs">
                                    <li class="active"><a data-toggle="tab" href="#nao-validadas"><i class="glyphicon glyphicon-info-sign"></i> Doações não validadas</a></li>
                                    <li><a data-toggle="tab" href="#validadas"><i class="glyphicon glyphicon-check"></i> Validadas</a></li>
                                </ul>


                                <div class="tab-content">
                                    <div id="nao-validadas" class="tab-pane fade in active">
                                        <br/>

                                        <table class="table table-striped table-hover">
                                            <thead>
                                                <tr>
                                                    <th>Nome do livro</th>
                                                    <th>Quantidade</th>
                                                    <th>Data</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach($doacoes as $doacao)
                                                    @if($doacao->validar == false)
                                                        <tr>
                                                            <td><a href="{{route('doacoes.show', ['id' => $doacao->id])}}">{{$doacao->livro}}</a></td>
                                                            <td>{{$doacao->quantidade}}</td>
                                                            <td>{{date_format($doacao->created_at, 'd/m/Y')}}</td>
                                                        </tr>
                                                    @endif
                                                @endforeach
                                            </tbody>
                                        </table>
                                    </div>

                                    <div id="validadas" class="tab-pane fade">
                                        <br/>

                                        <table class="table table-striped table-hover">
                                            <thead>
                                            <tr>
                                                <th>Nome do livro</th>
                                                <th>Quantidade</th>
                                                <th>Data</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            @foreach($doacoes as $doacao)
                                                @if($doacao->validar == true)
                                                    <tr>
                                                        <td><a href="{{route('doacoes.show', ['id' => $doacao->id])}}">{{$doacao->livro}}</a></td>
                                                        <td>{{$doacao->quantidade}}</td>
                                                        <td>{{date_format($doacao->created_at, 'd/m/Y')}}</td>
                                                    </tr>
                                                @endif
                                            @endforeach
                                            </tbody>
                                        </table>
                                    </div>
                                </div>

                        </div>

                    </div>
                </div>

                <hr/>

                <!--Posts informations -->
                <div class="col-md-12">



                </div>
            </div>
        </div>
    </div>
    </div>
@endsection

resources/views/profile.blade.php
@extends('app')

@section('title')
    {{$user->name}}
@endsection

@section('content')
    <div class="container">

        {{-- Error messages --}}
        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <strong>Opa!</strong> Existe algum problema com os valores informados<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <div class="row">
            <div class="col-md-3">
                <center><img width="160" height="160" class="img-circle" src="{{(Auth::user()->avatar) ? Auth::user()->avatar : "images/default-profile-picture.png"}}" alt="Imagem do perfil de {{Auth::user()->name}}"></center>
                <hr/>
                <p class="text-center">{{$user->name}}</p>
                <br/>
                <form action="{{route('profile.destroy', ['id' => Auth::user()->id])}}" method="post">
                    <input type="hidden" name="_token" value="{{csrf_token()}}"/>
                    <input type="hidden" name="_method" value="DELETE"/>

                    <center><button type="submit" class="btn btn-danger" disabled><i class="glyphicon glyphicon-remove"></i> Excluir conta</button></center>
                </form>
            </div>

            <div class="col-lg-9">

                <div class="row">

                    <ul class="nav nav-tabs">
                        <li class="active"><a data-toggle="tab" href="#minhas-doacoes">Minhas doações</span> </a></li>
                        <li><a data-toggle="tab" href="#minhas-postagens">Minhas postagens</a></li>
                    </ul>



                    <div class="tab-content">


                        <div id="minhas-doacoes" class="tab-pane fade in active">
                            <table class="table table-bordered table-hover">
                                <thead>
                                    <tr>
                                        <th>Livro</th>
                                        <th>Quantidade</th>
                                        <th>Entidade</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($user->doacoes as $doacao)
                                        <tr>
                                            <td>{{$doacao->livro}}</td>
                                            <td>{{$doacao->quantidade}}</td>
                                            <td>{{$doacao->entidade->name}}</td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>


                        <div id="minhas-postagens" class="tab-pane fade">


                            <!--form informations-->
                            <div class="col-md-12">

                                <div class="page-header">
                                    <h3>Leu um livro recentemente?</h3>
                                </div>


                                <div class="row">

                                    <div class="col-md-10 col-md-offset-1">

                                        <form action="{{route('posts.store')}}" method="post" class="form-horizontal">

                                            <input type="hidden" name="_token" value="{{csrf_token()}}"/>
                                            <input type="hidden" name="user_id" value="{{Auth::user()->id}}"/>

                                            <div class="form-group">
                                                <input type="text" name="title" id="title" value="{{old('title')}}" placeholder="Nome do livro" class="form-control" required="true"/>
                                            </div>

                                            <div class="form-group">
                                                <textarea name="body" id="body" class="form-control" placeholder="Compartilhe aqui conosco a sua experiência." rows="10" required="true">{{old('body')}}</textarea>
                                            </div>

                                            <div class="form-group">
                                                <button type="submit" class="btn btn-primary">
                                                    <i class="glyphicon glyphicon-send"></i> Publicar
                                                </button>
                                            </div>

                                        </form>

                                    </div>

                                </div>

                                <hr/>

                                <!--Posts informations -->
                                <div class="col-md-12">

                                    @foreach($user->posts->sortByDesc('created_at') as $post)

                                        <div class="panel panel-success">

                                            <div class="panel-heading panel-title text-right">{{date('d/m/Y à\s H:i', strtotime($post->created_at))}}
                                                <form action="{{route('posts.destroy', ['id' => $post->id])}}" method="post">
                                                    <input type="hidden" name="_token" value="{{csrf_token()}}"/>
                                                    <input type="hidden" name="_method" value="DELETE"/>
                                                    <button type="submit" class="btn btn-danger">Excluir</button>
                                                </form>
                                            </div>

                                            <div class="panel-body">
                                                <div class="page-header">
                                                    <h4><strong>{{$post->title}}</strong></h4>
                                                </div>

                                                <p>
                                                    {{$post->body}}
                                                </p>
                                            </div>
                                        </div>

                                    @endforeach

                                </div>

                            </div>
                        </div>

                        </div>
                    </div>



                </div>
            </div>
        </div>
    </div>
@endsection