app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

//página inicial da aplicação.
Route::get('/', ['as' => 'welcome', 'uses' => 'WelcomeController@index']);


//relacionado aos perfis de usuário.


//rota para o usuário acessar o seu perfil.
Route::get('profile',['as' => 'profile', 'uses' => 'HomeController@profile']);

//rota para que a entidade possa acessar o seu perfil.
Route::get('profile-entity',['as' => 'profile.entity', 'uses' => 'HomeController@profileEntity']);

Route::get('profile/busca', ['as' => 'profile.busca', 'uses' => 'HomeController@busca']);

Route::get('profile/{id}', ['as' => 'profile.details', 'uses' => 'HomeController@details']);

Route::delete('profile/{id}', ['as' => 'profile.destroy', 'uses' => 'HomeController@destroy']);

//pagina home com  a lista de perfis.
Route::get('home', ['as' => 'home', 'uses' => 'HomeController@home']);

//página com a lista de entidades.
Route::get('entidades', ['as' => 'entidades', 'uses' => 'EntidadeController@entidades']);

Route::get('entidades/create', ['as' => 'entidades.create', 'uses' => 'EntidadeController@create']);

Route::get('entidades/{id}', ['as' => 'entidades.details', 'uses' => 'EntidadeController@entidadesDetails']);

Route::post('entidades', ['as' => 'entidades.store', 'uses' => 'EntidadeController@store']);

//rotas relacionadas ao envio de imagem do perfil
Route::get('home/avatar', ['as' => 'avatar.create', 'uses' => 'HomeController@createAvatar']);
Route::post('home/avatar', ['as' => 'avatar.send', 'uses' => 'HomeController@sendAvatar']);

//logicas para seguir usuário...
Route::post('seguir', ['as' => 'seguir', 'uses' => 'HomeController@seguir']);

Route::post('deixar-de-seguir', ['as' => 'deixarDeSeguir', 'uses' => 'HomeController@deixarDeSeguir']);

Route::get('quem-me-segue', function(){
    return Auth::user()->theFriends()->count();
});

//controllers definidos para autenticação e restauração de senha.
Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

//serviço de integração com redes sociais.
Route::get('login/{provider?}', 'Auth\AuthController@login');

//resource controllers.
Route::resource("generolivro", 'GeneroLivroController');

Route::resource('posts', 'PostController');


//generos favoritos

Route::get('generos-favoritos/generos', ['as' => 'generosfavoritos.generos', 'uses' => 'GenerosFavoritosController@generos']);

Route::post('generos-favoritos/generos', ['as' => 'generosfavoritos.save', 'uses' => 'GenerosFavoritosController@save']);


//doação
Route::get('doacoes/{id}',['as' => 'doacoes.show', 'uses' => 'DoacaoController@show']);
Route::post('doacoes', ['as' => 'doacoes.send', 'uses' => 'DoacaoController@send']);
Route::put('doacoes', ['as' => 'doacoes.validar', 'uses' => 'DoacaoController@validar']);


//contato
Route::get('contato', ['as' => 'contato', 'uses' => 'ContatoController@contato']);

Route::post('contato', ['as' => 'contato.envia', 'uses' => 'ContatoController@enviaContato']);

Route::get('contato/{id}', ['as' => 'contato.ver', 'uses' => 'ContatoController@ver']);

Route::get('contatos', ['as' => 'contatos', 'uses' => 'ContatoController@listaContatos']);

app/GeneroLivro.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;

class GeneroLivro extends Model {

    protected $table = 'generolivros';

    protected $fillable = ['nome'];

    public function users()
    {
        return $this->belongsToMany('App\User', 'generolivros_users', 'user_id', 'generolivros_id');
    }
}

app/Http/Controllers/GeneroLivroController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Services\GeneroLivroService;
use Illuminate\Http\Request;
use Laracasts\Flash\Flash;

class GeneroLivroController extends Controller {

    const MENSSAGEM_REMOVIDO = "O gênero pode ter sido removido!";

    private $service;

    public function __construct(GeneroLivroService $service){
        $this->service = $service;

        //registra o middleware de controle de acesso para os recursos do controller.
        $this->middleware('admin');
    }

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$generos = $this->service->findAllPaginate();

        return view('generolivro.index')->with('generos', $generos);
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return view('generolivro.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store(Requests\GeneroLivroRequest $request)
	{
		$this->service->save($request);

        Flash::success('Gênero adicionado!');

        return redirect()->route('generolivro.index');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
        if($id == null){
            return abort(404);
        }
        else{

            $genero = null;

            $genero = $this->service->findById($id);

            if($genero){
                return view('generolivro.show')->with('genero', $genero);
            }
            else{
                Flash::warning(self::MENSSAGEM_REMOVIDO);

                return redirect()->route("generolivro.index");
            }

        }
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
        if($id == null){
            abort(404);
        }else{
            $genero = null;

            $genero = $this->service->findById($id);

            if($genero){
                return view('generolivro.edit')->with('genero', $genero);
            }
            else{
                Flash::warning(self::MENSSAGEM_REMOVIDO);
                return redirect()->route('generolivro.index');
            }

        }

	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update(Requests\GeneroLivroRequest $request, $id)
	{
        if($id == null){
            abort(404);
        }else
        {
            $genero = $this->service->update($request, $id);

            if($genero){

                Flash::warning("Gênero atualizado!");

                return redirect()->route('generolivro.index');
            }
            else{
                Flash::warning("Não foi possível atualizar. " . self::MENSSAGEM_REMOVIDO);
                return redirect()->route('generolivro.index');
            }
        }
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
        if($id == null){
            abort(404);
        }
        else{
            if($this->service->delete($id)){
                Flash::success("Gênero removido!");

                return redirect()->route('generolivro.index');
            }
            else{
                Flash::warning(self::MENSSAGEM_REMOVIDO);
                return redirect()->route('generolivro.index');
            }
        }
	}

}

resources/views/generolivro/create.blade.php
@extends('app')

@section('title')
    Adicionar novo gênero
@endsection

@section('content')
    <div class="container">

        <div class="page-header">
            <h1>Adicionar novo gênero</h1>
        </div>

        <div class="row">

            @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <div class="col-lg-6 col-lg-offset-3">
                <form action="{{route('generolivro.store')}}" class="form-horizontal" method="post">
                    <input type="hidden" name="_token" value="{{csrf_token()}}"/>

                    <div class="form-group">
                        <label for="nome">Nome</label>
                        <input type="text" class="form-control" id="nome" name="nome" value="{{old('nome')}}" placeholder="Gênero" required="true">

                        <br/>
                        <input type="submit" value="Adicionar" class="btn btn-primary"/>
                        <input type="reset" value="Limpar" class="btn btn-warning"/>
                        <a href="{{route('generolivro.index')}}" class="btn btn-danger">Cancelar</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/generolivro/edit.blade.php
@extends('app')

@section('title')

@endsection

@section('content')
    <div class="container">

        <div class="page-header">
            <h1>Editando gênero</h1>
        </div>

        <div class="row">

            @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <div class="col-lg-6 col-lg-offset-3">
                <form action="{{route('generolivro.update', ['id' => $genero->id])}}" class="form-horizontal" method="post">
                    <input type="hidden" name="_token" value="{{csrf_token()}}"/>
                    <input type="hidden" name="_method" value="PUT"/>

                    <div class="form-group">
                        <label for="nome">Nome</label>
                        <input type="text" class="form-control" id="nome" name="nome" value="{{$genero->nome}}" placeholder="Gênero">

                        <br/>
                        <input type="submit" value="Salvar" class="btn btn-primary"/>
                        <input type="reset" value="Limpar" class="btn btn-warning"/>
                        <a href="{{route('generolivro.index')}}" class="btn btn-danger">Cancelar</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/generolivro/index.blade.php
@extends('app')

@section('title')
    Lista de gêneros
@endsection


@section('content')
    <div class="container">

        <div class="page-header">
            <h1>Lista de gêneros</h1>
        </div>

        <div class="row">
            <div class="col-lg-6 col-lg-offset-3">

                <span class="left"><a href="{{route('generolivro.create')}}" class="btn btn-success">Adicionar novo</a></span>

                <br/>
                <br/>

                <table class="table table-bordered table-striped table-hover">
                    <thead>
                        <tr>
                            <th>Nome</th>
                            <th>Editar</th>
                            <th>Remover</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($generos as $genero)
                            <tr>
                                <td>{{$genero->nome}}</td>
                                <td><a href="{{route('generolivro.edit', ['id' => $genero->id])}}">Editar</a></td>
                                <td>
                                    <form action="{{route('generolivro.destroy', ['id' => $genero->id])}}" method="post">
                                        <input type="hidden" name="_token" value="{{csrf_token()}}"/>
                                        <input type="hidden" name="_method" value="DELETE"/>
                                        <input type="submit" value="Remover" class="btn btn-danger"/>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>

                {!!$generos->render()!!}
            </div>
        </div>
    </div>
@endsection